name:                elm-prelude
version:             0.1.0.0
github:              "miniBill/elm-prelude"
license:             BSD3
author:              "Leonardo Taglialegne"
maintainer:          "cmt.miniBill@gmail.com"
copyright:           "2019 Leonardo Taglialegne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/miniBill/elm-prelude#readme>

dependencies: []


library:
  source-dirs: src
  exposed-modules:
  - Char
  - Compat
  - Dict
  - List
  - Maybe
  - Prelude
  - Result
  - String
  - Tuple
  other-modules:
  - Kernel
  default-extensions:
  - Strict
  - StrictData
  - OverloadedStrings
  ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  dependencies:
  - base >= 4.7 && < 5
  - containers >=0.5 && <0.7
  - text >=1.2 && <1.3

tests:
  elm-prelude-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
    - Strict
    - StrictData
    - OverloadedStrings
    ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-prelude
