name:                elm-tea-example
version:             0.1.0.0
github:              "miniBill/elm-tea-example"
license:             BSD3
author:              "Leonardo Taglialegne"
maintainer:          "cmt.miniBill@gmail.com"
copyright:           "2019 Leonardo Taglialegne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/miniBill/elm-tea-example#readme>

dependencies:
- elm-prelude >=0.1 && <0.2

executables:
  elm-tea-example:
    main: Opinion.hs
    source-dirs: src
    other-modules: []
    default-extensions:
    - Strict
    - StrictData
    - OverloadedStrings
    ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-tea >=0.1 && <0.2
    - elm-http >=0.1 && <0.2
